# docker-compose version
version: '3'

services:
  redis:
    image: "redis:alpine"

  demo:
    container_name: django_demo_container
    build:
      # path to the Dockerfile
      context: ./Demo
    restart: always
    # format : https://docs.docker.com/engine/reference/builder/#cmd
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate && 
                    uwsgi --ini uwsgi.ini"
    volumes:
      - uwsgi.sock:/Demo/uwsgi.sock
      - demo_data:/Demo
    # environment:
    #   - 
    env_file:
      - .env
    depends_on:
      - redis
      - db

  nginx:
    container_name: nginx-container
    build: 
      context: ./nginx
    restart: always
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - uwsgi.sock:/Demo/uwsgi.sock
      - demo_data:/Demo
    depends_on:
      - demo
      - redis

  db:
      container_name: postgres
      image: postgres:13-alpine
      restart: always
      # environment:
      # - 
      env_file:
      - .env
      volumes:
        - postgres_data:/var/lib/postgresql/data/

  celery_worker:
    container_name: celery_worker
    build: ./Demo
    # environment:
    # -
    env_file:
      - .env
    volumes:
      - demo_data:/Demo
    command: sh -c "celery -A Demo worker -l info"
    depends_on:
      - redis

volumes:
  postgres_data:
  uwsgi.sock:
  demo_data:



### About Docker volume ###
# CDp : Container data path
# HDp : Host data path

# volume types :
#   1.Host volume (self-define path of both)
#      -(HDp) : (CDp)
#   2.Anonymous volume (only define CDp ,but let HDp set by default path)
#      -(CDp)  (Default HDp : /var/lib/docker/volumes)
#   3.Named volume (only define Cd ,but let Hd set by default path with a name tag)
#      -(<name>) : (CDp)  (name = default HDp : /var/lib/docker/volumes)

# commands
#   docker volume ls
#   docker volume inspect <vol_name>
#   docker volume rm <vol_name>


